// List of major cities in Pakistan
export const pakistanCities = [
  "Karachi",
  "Lahore", 
  "Islamabad",
  "Rawalpindi",
  "Faisalabad",
  "Multan",
  "Gujranwala",
  "Peshawar",
  "Quetta",
  "Sialkot",
  "Sargodha",
  "Bahawalpur",
  "Sukkur",
  "Jhang",
  "Sheikhupura",
  "Larkana",
  "Rahim Yar Khan",
  "Gujrat",
  "Kasur",
  "Mardan",
  "Mingora",
  "Nawabshah",
  "Chiniot",
  "Kotri",
  "Kāmoke",
  "Hafizabad",
  "Kohat",
  "Jacobabad",
  "Shikarpur",
  "Muzaffargarh",
  "Khanpur",
  "Gojra",
  "Bahawalnagar",
  "Abbottabad",
  "Muridke",
  "Pakpattan",
  "Khuzdar",
  "Jhelum",
  "Kot Addu",
  "Turbat",
  "Dera Ghazi Khan",
  "Nawabshah",
  "Chishtian",
  "Hasilpur",
  "Attock",
  "Muzaffarabad",
  "Mianwali",
  "Burewala",
  "Mirpur Khas",
  "Chakwal",
  "Tando Allahyar",
  "Kotri",
  "Vihari",
  "Nowshera",
  "Swat",
  "Okara",
  "Wazirabad",
  "Daska",
  "Mandi Bahauddin",
  "Jatoi",
  "Kotli",
  "Haripur",
  "Matiari",
  "Kot Radha Kishan",
  "Hangu",
  "Taxila",
  "Narowal",
  "Shakargarh",
  "Sahiwal",
  "Sanghar",
  "Mirpur",
  "Kamber Ali Khan",
  "Umerkot",
  "Chaman",
  "Kot Mumin",
  "Kotli Loharan",
  "Kot Diji",
  "Kot Sultan",
  "Kot Mithan",
  "Kot Addu",
  "Kot Radha Kishan",
  "Kot Ghulam Muhammad",
  "Kot Adu",
  "Kot Samaba",
  "Kot Diji",
  "Kot Mithan",
  "Kot Sultan",
  "Kot Loharan",
  "Kot Mumin",
  "Kot Diji",
  "Kot Sultan",
  "Kot Mithan",
  "Kot Addu",
  "Kot Radha Kishan",
  "Kot Ghulam Muhammad",
  "Kot Adu",
  "Kot Samaba"
];

export const getCityOptions = () => {
  return pakistanCities.map(city => ({
    value: city,
    label: city
  }));
};

